export const bobqiushao = {
  name: 'bobqiushao',
  description: '秋少官网统一风格（极简纸质感）',
  container: 'font-family: "STKaiti", "华文楷体", serif; font-size: 17px; line-height: 1.9; color: #1A1A1A; max-width: 100%; padding: 20px; background-color: #FAF9F6;',
  h1: 'font-family: "PingFang SC", "Microsoft YaHei", sans-serif; font-size: 28px; font-weight: 500; color: #1A1A1A; line-height: 1.3; margin: 0 0 24px; letter-spacing: -0.01em;',
  h2: 'font-family: "PingFang SC", "Microsoft YaHei", sans-serif; font-size: 23px; font-weight: 600; color: #1A1A1A; line-height: 1.4; margin: 56px 0 19px; padding-bottom: 8px; border-bottom: 1px solid #E5E2D9; letter-spacing: -0.01em;',
  h3: 'font-family: "PingFang SC", "Microsoft YaHei", sans-serif; font-size: 18px; font-weight: 500; color: #4A4A4A; line-height: 1.4; margin: 40px 0 13px; padding-left: 13px; border-left: 3px solid #6B4423;',
  p: 'font-family: "STKaiti", "华文楷体", serif; font-size: 17px; color: #1A1A1A; line-height: 1.9; margin: 0 0 29px;',
  strong: 'font-weight: 600; color: #1A1A1A;',
  em: 'font-style: italic;',
  a: 'color: #6B4423; text-decoration: underline; text-underline-offset: 4px;',
  blockquote: 'border-left: 3px solid #E5E2D9; background-color: #F2F0EA; padding: 16px 24px; margin: 35px 0; border-radius: 0 4px 4px 0; color: #4A4A4A; font-style: italic; line-height: 1.8;',
  code: 'background-color: #F2F0EA; padding: 4px 8px; border-radius: 4px; font-family: "JetBrains Mono", "Consolas", monospace; font-size: 15px; color: #1A1A1A;',
  pre: 'background-color: #282c34; color: #abb2bf; padding: 20px; border-radius: 8px; overflow-x: auto; margin: 35px 0; font-size: 14px; line-height: 1.6;',
  ul: 'padding-left: 29px; margin: 0 0 29px; list-style-type: disc;',
  ol: 'padding-left: 29px; margin: 0 0 29px; list-style-type: decimal;',
  li: 'font-family: "STKaiti", "华文楷体", serif; margin: 0 0 13px; line-height: 1.8; color: #1A1A1A;',
  table: 'width: 100%; border-collapse: collapse; margin: 32px 0; font-size: 15px; overflow-x: auto; display: block;',
  th: 'background-color: #F2F0EA; padding: 10px 13px; border: 1px solid #E5E2D9; text-align: left; font-weight: 600; font-size: 14px; color: #4A4A4A;',
  td: 'padding: 10px 13px; border: 1px solid #E5E2D9; color: #1A1A1A; line-height: 1.5;',
  img: 'max-width: 100%; height: auto; display: block; margin: 40px auto;',
  hr: 'border: none; border-top: 1px solid #E5E2D9; margin: 56px 0;',
};
